restart-times: 1
jobscript: "slurm-jobscript.sh"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 2
jobs: 30
keep-going: true
printshellcmds: true
jobname: "{name}.{jobid}.snakejob.sh"
conda-prefix: /mnt/beegfs/userdata/y_pradat/snakemake/conda
apptainer-prefix: /mnt/beegfs/userdata/y_pradat/snakemake/singularity
wrapper-prefix: https://github.com/snakemake/snakemake-wrappers/raw/
software-deployment-method:
  - "apptainer"
  - "conda"
executor: "slurm-gustave-roussy"
rerun-triggers: "mtime"
benchmark-extended: true
default-resources:
  - "tmpdir='/mnt/beegfs/userdata/y_pradat/tmp'"
